# Generated by Django 3.0.7 on 2020-06-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denm_cam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
    ]
