# Generated by Django 3.0.7 on 2020-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denm_cam', '0002_cam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cam',
            name='data',
        ),
        migrations.RemoveField(
            model_name='denm',
            name='data',
        ),
        migrations.AddField(
            model_name='cam',
            name='test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denm',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
