# Generated by Django 3.0.7 on 2020-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denm_cam', '0003_auto_20200623_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='test',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='denm',
            name='test',
            field=models.BinaryField(),
        ),
    ]
