# Generated by Django 3.0.7 on 2020-06-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denm_cam', '0004_auto_20200623_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cam',
            old_name='test',
            new_name='test_binary',
        ),
        migrations.RenameField(
            model_name='denm',
            old_name='test',
            new_name='test_binary',
        ),
    ]
