# Generated by Django 3.0.7 on 2020-06-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denm_cam', '0006_auto_20200623_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cam',
            old_name='test_binary',
            new_name='chars',
        ),
        migrations.RenameField(
            model_name='denm',
            old_name='test_binary',
            new_name='chars',
        ),
    ]
